# Generated by Django 4.0.3 on 2022-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default='', max_length=100)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
