# Generated by Django 4.0.3 on 2022-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
