# Generated by Django 4.0.3 on 2022-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_end_time_alter_todo_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
